# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'PrettyIcons' do

end

target 'PrettyIconsTests' do

end

target 'PrettyIconsUITests' do

end

pod 'Firebase', '>=2.5.0'
